name: Code standardizer hook for PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [develop]
  push:
    branches: [develop]

jobs:
  enforce-code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.3.0'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      # If prettier or jshint fails, push or PR will be rejected
      - name: Commit and Push Changes with linting and auto-format
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Intentar hacer commit
          git add .
          git commit -m "🚀 Auto-format code and linting check"
          COMMIT_STATUS=$?

          if [ $COMMIT_STATUS -eq 0 ]; then
            echo "✅ Commit checks OK, continuing commiting"
            git push
          else
            echo "❌ Commit with errors, aborting"
            exit 1
          fi
